/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import controller.AdministradorController;
import controller.UsuarioController;
import javax.swing.JOptionPane;
import model.Administrador;
import model.Usuario;

/**
 *
 * @author alexandre
 */
public class AdministradorFrame extends javax.swing.JFrame {
    private Administrador admin = null;
    /**
     * Creates new form MenuAdministradorFrame
     */
    public AdministradorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCpf = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();
        jBtLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTxtDataNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtCargo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBtAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        infoPessoais = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cbUsuario = new javax.swing.JCheckBox();
        cbAdmin = new javax.swing.JCheckBox();
        bVerUsuarios = new javax.swing.JButton();
        bVerAdmins = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        lStatus = new javax.swing.JLabel();
        chAtivo = new javax.swing.JCheckBox();
        chInativo = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtConfirmarSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jTxtCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Menu Administrador");

        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setText("Senha:");

        jCpf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jSenha.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jBtLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jBtLogin.setText("Logar");
        jBtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setText("Data de nascimento:");

        jTxtDataNascimento.setText("dd/mm/aaaa");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("Cargo:");

        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("Informações pessoais");

        jSeparator2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("Alterar informações");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("Senha:");

        infoPessoais.setText("-");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel11.setText("ID: *");

        jSeparator3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        cbUsuario.setText("Usuário");

        cbAdmin.setText("Administrador");

        bVerUsuarios.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        bVerUsuarios.setText("Visualizar todos os usuários");
        bVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerUsuariosActionPerformed(evt);
            }
        });

        bVerAdmins.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        bVerAdmins.setText("Visualizar todos os administradores");
        bVerAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerAdminsActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lStatus.setText("Status:");

        chAtivo.setText("Ativo");

        chInativo.setText("Inativo");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("Perfil:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel13.setText("Confirmar Senha:");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel14.setText("CPF:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bVerUsuarios)
                                .addGap(18, 18, 18)
                                .addComponent(bVerAdmins))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bFechar)
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jBtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btCadastrar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTxtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(lStatus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chInativo)
                                            .addComponent(chAtivo))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(infoPessoais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtAlterar)
                            .addComponent(cbUsuario)
                            .addComponent(cbAdmin)
                            .addComponent(btCadastrar)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bVerUsuarios)
                            .addComponent(bVerAdmins)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lStatus)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chAtivo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chInativo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLoginActionPerformed
        // TODO add your handling code here:
        admin = AdministradorController.verificarLogin(jCpf.getText(), jSenha.getText());
        if(admin != null) {
            String status;
            if(admin.getStatus() == 1) {
                status = "ativo";
            } else {
                status = "inativo";
            }
            infoPessoais.setText("ID: "+admin.getId()+", CPF: "+admin.getCpf()+", Nome: "+admin.getNome()+", Email: "+admin.getEmail()+", Data de Nascimento: "
                +admin.getDataNascimento()+", Cargo: "+admin.getCargo()+", Status: "+status);

        } else {
            JOptionPane.showMessageDialog(this, "Senha e/ou ID incorretos!");
        }
    }//GEN-LAST:event_jBtLoginActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        // TODO add your handling code here:
        if(admin != null) {
            if(!jtxtID.getText().equals("")) {
                if(cbAdmin.isSelected() && !cbUsuario.isSelected()) { //Administrador  
                    if(jTxtSenha.getText().equals(jTxtConfirmarSenha.getText())) {
                        int statusCadastro = 1;
                        if(!chAtivo.isSelected() && chInativo.isSelected()) {
                            statusCadastro = 2;
                        }
                        AdministradorController.atualizar(Integer.parseInt(jtxtID.getText()), jTxtNome.getText(), jTxtEmail.getText()
                        , jTxtSenha.getText(), jTxtDataNascimento.getText(), jTxtCargo.getText(), statusCadastro, jTxtCpf.getText());

                        JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(this, "As senhas não são compatíveis!");
                    }
                } else if(!cbAdmin.isSelected() && cbUsuario.isSelected()) { //Usuario
                    if(jTxtSenha.getText().equals(jTxtConfirmarSenha.getText())) {
                        int statusCadastro = 1;
                        if(!chAtivo.isSelected() && chInativo.isSelected()) {
                            statusCadastro = 2;
                        }
                        UsuarioController.atualizar(Integer.parseInt(jtxtID.getText()), jTxtNome.getText(), jTxtEmail.getText()
                        , jTxtSenha.getText(), jTxtDataNascimento.getText(), jTxtCargo.getText(), statusCadastro, jTxtCpf.getText());
                        JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(this, "As senhas não são compatíveis!");
                    }
                } else if(!cbAdmin.isSelected() && !cbUsuario.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Selecione um perfil!");
                } else if(cbAdmin.isSelected() && cbUsuario.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Selecione apenas um perfil!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "O campo ID é obrigatório!");
            }
            admin = AdministradorController.infoPessoais(admin.getId());
            String status;
            if(admin.getStatus() == 1) {
                status = "ativo";
            } else {
                status = "inativo";
            }
            infoPessoais.setText("ID: "+admin.getId()+", CPF: " +admin.getCpf()+", Nome: "+admin.getNome()+", Email: "+admin.getEmail()+", Data de Nascimento: "
                +admin.getDataNascimento()+", Cargo: "+admin.getCargo()+", Status: "+status);
        } else {
            JOptionPane.showMessageDialog(this, "Efetue o login antes!");
        }
        jTxtNome.setText("");
        jTxtCpf.setText("");
        jTxtEmail.setText("");
        jTxtSenha.setText("");
        jTxtConfirmarSenha.setText("");
        jTxtDataNascimento.setText("dd/mm/aaaa");
        jTxtCargo.setText("");
        cbAdmin.setSelected(false);
        cbUsuario.setSelected(false);
        chInativo.setSelected(false);
        chAtivo.setSelected(false);
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bFecharActionPerformed

    private void bVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerUsuariosActionPerformed
        // TODO add your handling code here:
        if(admin != null) {
        UsuarioController.tableUsuariosFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Efetue o login antes!");
        }
    }//GEN-LAST:event_bVerUsuariosActionPerformed

    private void bVerAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerAdminsActionPerformed
        // TODO add your handling code here:
        if(admin != null) {
        AdministradorController.tableAdministradoresFrame();
        } else {
            JOptionPane.showMessageDialog(this, "Efetue o login antes!");
        }
    }//GEN-LAST:event_bVerAdminsActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        if(admin != null) {
            if(jtxtID.getText().equals("") && !jTxtCpf.getText().equals("") && !jTxtEmail.getText().equals("") && !jTxtNome.getText().equals("")
                    && !jTxtSenha.getText().equals("") && !jTxtConfirmarSenha.getText().equals("") 
                    && !jTxtDataNascimento.getText().equals("dd/mm/aaaa") && !jTxtCargo.getText().equals("") 
                    && (!chAtivo.isSelected() || !chInativo.isSelected())) {
                if(cbAdmin.isSelected() && !cbUsuario.isSelected()) { //Admin
                    Administrador novoAdmin = AdministradorController.verificarCpf(jTxtCpf.getText());
                    if(novoAdmin == null) {
                        if(jTxtSenha.getText().equals(jTxtConfirmarSenha.getText())) {
                            int statusCadastro = 1;
                            if(!chAtivo.isSelected() && chInativo.isSelected()) {
                                statusCadastro = 2;
                            }
                            AdministradorController.cadastrar(jTxtNome.getText(), jTxtEmail.getText()
                            , jTxtSenha.getText(), jTxtDataNascimento.getText(), jTxtCargo.getText(), statusCadastro, jTxtCpf.getText());
                            
                            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
                        } else {
                        JOptionPane.showMessageDialog(this, "As senhas não são compatíveis!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "CPF já cadastrado!");
                    }
                } else if(!cbAdmin.isSelected() && cbUsuario.isSelected()) { //Usuario
                    Usuario novoUsuario = UsuarioController.verificarCpf(jTxtCpf.getText());
                    if(novoUsuario == null) {
                        if(jTxtSenha.getText().equals(jTxtConfirmarSenha.getText())) {
                            int statusCadastro = 1;
                            if(!chAtivo.isSelected() && chInativo.isSelected()) {
                                statusCadastro = 2;
                            }
                            UsuarioController.cadastrar(jTxtNome.getText(), jTxtEmail.getText(), 
                                    jTxtSenha.getText(), jTxtDataNascimento.getText(), jTxtCargo.getText(), statusCadastro, jTxtCpf.getText());
                            
                            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
                        } else {
                            JOptionPane.showMessageDialog(this, "As senhas não são compatíveis!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "CPF já cadastrado!");
                    }
                } else if(!cbAdmin.isSelected() && !cbUsuario.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Selecione um perfil!");
                } else if(cbAdmin.isSelected() && cbUsuario.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Selecione apenas um perfil!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios para cadastro!\nCampo ID deve ficar vazio!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Efetue o login antes!");
        }
        jTxtNome.setText("");
        jTxtEmail.setText("");
        jTxtSenha.setText("");
        jTxtCpf.setText("");
        jTxtConfirmarSenha.setText("");
        jTxtDataNascimento.setText("dd/mm/aaaa");
        jTxtCargo.setText("");
        cbAdmin.setSelected(false);
        cbUsuario.setSelected(false);
        chInativo.setSelected(false);
        chAtivo.setSelected(false);
    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFechar;
    private javax.swing.JButton bVerAdmins;
    private javax.swing.JButton bVerUsuarios;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JCheckBox cbAdmin;
    private javax.swing.JCheckBox cbUsuario;
    private javax.swing.JCheckBox chAtivo;
    private javax.swing.JCheckBox chInativo;
    private javax.swing.JLabel infoPessoais;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtLogin;
    private javax.swing.JTextField jCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTxtCargo;
    private javax.swing.JPasswordField jTxtConfirmarSenha;
    private javax.swing.JTextField jTxtCpf;
    private javax.swing.JTextField jTxtDataNascimento;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JPasswordField jTxtSenha;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JLabel lStatus;
    // End of variables declaration//GEN-END:variables
}
