/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import controller.AdministradorController;
import controller.SistemaController;
import controller.UsuarioController;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author alexandre
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginUsuarioFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLLogin = new javax.swing.JLabel();
        jBLoginUser = new javax.swing.JButton();
        jBRecuperarSenha = new javax.swing.JButton();
        jBLoginAdmin = new javax.swing.JButton();
        jBCadastrarUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLLogin.setFont(new java.awt.Font("Kannada MN", 1, 36)); // NOI18N
        jLLogin.setText("Sistema SAKS");

        jBLoginUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBLoginUser.setText("Logar Usuário");
        jBLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginUserActionPerformed(evt);
            }
        });

        jBRecuperarSenha.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBRecuperarSenha.setText("Recuperar Senha");
        jBRecuperarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecuperarSenhaActionPerformed(evt);
            }
        });

        jBLoginAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBLoginAdmin.setText("Logar Administrador");
        jBLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginAdminActionPerformed(evt);
            }
        });

        jBCadastrarUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBCadastrarUser.setText("Cadastrar");
        jBCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLogin)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCadastrarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRecuperarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLLogin)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLoginUser)
                    .addComponent(jBLoginAdmin))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRecuperarSenha)
                    .addComponent(jBCadastrarUser))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginUserActionPerformed
       UsuarioController.usuarioFrame();
    }//GEN-LAST:event_jBLoginUserActionPerformed

    private void jBCadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarUserActionPerformed
        // TODO add your handling code here:
        UsuarioController.cadastrarFrame();
    }//GEN-LAST:event_jBCadastrarUserActionPerformed

    private void jBRecuperarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecuperarSenhaActionPerformed
        // TODO add your handling code here:
        SistemaController.recuperarSenhaFrame();
    }//GEN-LAST:event_jBRecuperarSenhaActionPerformed

    private void jBLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginAdminActionPerformed
        // TODO add your handling code here:
        AdministradorController.administradorFrame();
    }//GEN-LAST:event_jBLoginAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarUser;
    private javax.swing.JButton jBLoginAdmin;
    private javax.swing.JButton jBLoginUser;
    private javax.swing.JButton jBRecuperarSenha;
    private javax.swing.JLabel jLLogin;
    // End of variables declaration//GEN-END:variables
}
